nome = input("Digite seu nome: ")
sobrenome = input("Digite seu sobrenome: ")
print(f"seu nome é {nome}")
print(nome, sobrenome)
print(nome, end="\n")
print(sobrenome, end="\n")
print(nome, end="...")
print(sobrenome, end="...")
print("testando", end="...\n")
print(nome, sobrenome, end="...\n")
print(nome, sobrenome, sep="#")
print(nome, sobrenome, sep="#", end="...\n")